### ISSUE TITLE
Great companion to Snap Links Plus

### ISSUE THREAD

**Issue by davidhedlund** [SalvatoreMeschini/CheckThemAll#3]
I'll say that:

> The fastest way to use CheckThemAll is by using [Snap Links Plus](https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/) as an ad-hoc.

Can you please mention this at https://addons.mozilla.org/en-US/firefox/addon/checkthemall/ ?

**Comment by SalvatoreMeschini** [comment]
I could do that, but how can CheckThemAll be used as a companion to Snap Links + ?

**Comment by davidhedlund** [comment]
By using Snap Links+ to check/uncheck the checkboxes instead of using the context menu.

**Comment by davidhedlund** [comment]
It was apparently possible to do this in Snap Links Plus [3.1.0.4](https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/?page=1#version-3.1.0.4) but there was a bug that prevented it to work.

The bug has been fixed in Snap Links Plus version 3.1.2b1 (released in 3.1.2.3) who's log reads:

> ...
> * Fixed an issue with radio button selection
> * Fixed an issue with checkboxes
> ...

**Comment by davidhedlund** [comment]
https://github.com/cpriest/SnapLinksPlus/issues/227
