### ISSUE TITLE
Get listed as CheckFox replacement

### ISSUE THREAD

**Issue by nemobis** [SalvatoreMeschini/CheckThemAll#4]
Ottimo lavoro, it works as advertised.

As a CheckFox user, I want to easily find CheckThemAll as its replacement when I click the [Find a  replacement](https://addons.mozilla.org/find-replacement/?guid={BAEC7B80-9A31-47b2-A68B-DCAC8DF48E87}) link.

I'm told you can achieve that by [https://discourse.mozilla.org/t/favorite-webextensions/17087/171 asking on the forum] as suggested in the [blog post](https://blog.mozilla.org/addons/2017/10/26/helping-find-compatible-extensions/). Presumably, some [AMO](https://wiki.mozilla.org/AMO) moderators/admins act on the suggestions.

Grazie.

**Comment by SalvatoreMeschini** [comment]
Grazie a te!

I'm going to check if CheckThemAll can be added to the "Find a replacement"
link.

Salvatore

2018-02-09 9:16 GMT+01:00 nemobis <notifications@github.com>:

**Comment by nemobis** [comment]
Bene! C'era anche https://addons.mozilla.org/en-US/firefox/addon/multiple-checkbox-checker/

**Comment by SalvatoreMeschini** [comment]
Thanks for your advice, I applied for https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Featured.

Closing this issue.
