### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by Higgbo** [SalvatoreMeschini/CheckThemAll#5]
CheckThemAll used to be a great solution for me. Probably after a Firefox upgrade, it stopped working. The webpage I use it on didn't change, but when I expand the cursor, it does not (and never did) highlight the box it would check. It worked once or twice since, but not since (for weeks). The first column in the photo is blurred to mask confidential data.
![zzz5](https://user-images.githubusercontent.com/38354445/43646160-1f2d8280-9702-11e8-9155-48f0cbecba72.png)

**Comment by SalvatoreMeschini** [comment]
CheckThemAll did not change either, so if you are 100% sure about the fact that the page did not change, it may be something related to how Firefox / you apply the selection to that page.

In order to work properly, the selection must **include** those checkboxes. Are you sure that they are part of the selection?

Could you please try again, just to be sure that you are selecting them (from the screenshot it seems that only columns 2 - 6 are selected).

**Comment by Higgbo** [comment]
Thanks for responding. The cursor will not expand to highlight the boxes themselves. It never did, but it used to work that way. I do a weekly download on Fridays and have to check about 30 to 35 boxes of the rows I need. The page shows data files for 15 days of data, with about 7 files per day. As I said, I do this weekly , so I need to capture the 35 rows at the bottom. I start at the end of the last line and go up to the left side of the box at the top row. The week it stopped working might have coincided with a Firefox upgrade. But a couple of weeks later, it worked again, but only that time. For the past 5 or 6 week, I have to check them manually. I was probably using CheckThemAll for at least a year prior to the issue. Before that, I used a similar extension called CheckFox (I think that was it). I’ll let you know what happens with this Friday’s download.

Robert D. Higgins
Dalton Financial LLC
910 Greentree Dr.
Charlotte, NC 28211

Direct: 704.366.8676
Mobile: 704.907.0315
Fax:     866.282.2521
Email: bob@daltonfin.com<mailto:bob@daltonfin.com>
Website: www.daltonfin.com

The information contained in this email is being transmitted to and is intended for the use of only the individual(s) to whom it is addressed. If the reader of this message is not the intended recipient, you are hereby advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please immediately delete.

**Comment by SalvatoreMeschini** [comment]
As you discovered, it's just a matter of how the selection is made:

1) If you start in the margin at the top left, **it works**. 
2) If you start at the bottom right margin and expand up to the left, it doesn’t work.

CheckThemAll relies on the selection made by the user / Firefox, so please use the 1st selection method.

**Comment by Higgbo** [comment]
OK, today is time for my weekly Friday download. After many trials, it works when I start at the top right and expand to the bottom left, or in the opposite direction (bottom left to top right). Once it worked when starting at the bottom right, but never from the top left. Crazy. At least I know it is sensitive to the starting point, and can change depending on the weather.

Have a nice weekend!

Robert D. Higgins
Dalton Financial LLC
910 Greentree Dr.
Charlotte, NC 28211

Direct: 704.366.8676
Mobile: 704.907.0315
Fax:     866.282.2521
Email: bob@daltonfin.com<mailto:bob@daltonfin.com>
Website: www.daltonfin.com

The information contained in this email is being transmitted to and is intended for the use of only the individual(s) to whom it is addressed. If the reader of this message is not the intended recipient, you are hereby advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please immediately delete.

**Comment by SalvatoreMeschini** [comment]
Hi,

I guess that, depending on how the selection is performed, Firefox includes
/ excludes the checkboxes from being selected.
CheckThemAll just "scans" the selection looking for checkboxes, so a lot
depends if they are included or not in the selection.

Maybe just a small difference in how the range is selected makes a huge
difference in that regard.

But I'm glad that you found a viable "workaround"!

Salvatore




Il giorno ven 10 ago 2018 alle ore 22:19 Higgbo <notifications@github.com>
ha scritto:
